CREATE DATABASE QLGV;

USE QLGV;
DROP DATABASE QLGV;

CREATE TABLE KHOA(
    MAKHOA VARCHAR(4) PRIMARY KEY ,
    TENKHOA VARCHAR(40),
    NGTLAP DATETIME,
    TRGKHOA CHAR(4),
);

CREATE TABLE MONHOC(
  MAMH VARCHAR(10) PRIMARY KEY,
  TENMH VARCHAR(40),
  TCLT TINYINT,
  TCTH TINYINT,
  MAKHOA VARCHAR(4),
);

CREATE TABLE DIEUKIEN(
    MAMH VARCHAR(10),
    MAMH_TRUOC VARCHAR(10),
    CONSTRAINT PK_DIEUKIEN PRIMARY KEY(MAMH,MAMH_TRUOC),
);

CREATE TABLE GIAOVIEN(
    MAGV CHAR(4) PRIMARY KEY,
    HOTEN VARCHAR(40),
    HOCVI VARCHAR(10),
    HOCHAM VARCHAR(10),
    GIOITINH VARCHAR(3),
    NGSINH DATETIME,
    NGVL DATETIME,
    HESO NUMERIC(4,2),
    MUCLUONG MONEY,
    MAKHOA VARCHAR(4),
);

CREATE TABLE LOP(
    MALOP CHAR(3) PRIMARY KEY ,
    TENLOP VARCHAR(40),
    TRGLOP CHAR(5),
    SISO TINYINT,
    MAGVCN CHAR(4),
);

CREATE TABLE HOCVIEN(
    MAHV CHAR(5) PRIMARY KEY,
    HO VARCHAR(40),
    TEN VARCHAR(10),
    GIOITINH VARCHAR(3),
    NOISINH VARCHAR(40),
    NGSINH DATETIME,
    MALOP CHAR(3),
);

CREATE TABLE GIANGDAY(
    MALOP CHAR(3),
    MAMH VARCHAR(10),
    MAGV CHAR(4),
    HOCKY TINYINT,
    NAM SMALLINT,
    TUNGAY DATETIME,
    DENNGAY DATETIME,
    CONSTRAINT PK_GIANGDAY PRIMARY KEY(MALOP,MAMH),
);

CREATE TABLE KETQUATHI(
    MAHV CHAR(5),
    MAMH VARCHAR(10),
    LANTHI TINYINT,
    NGTHI DATETIME,
    DIEM NUMERIC(4,2),
    KQUA VARCHAR(10),
    CONSTRAINT PK_KETQUATHI PRIMARY KEY(MAHV,MAMH,LANTHI),
);

-- CREATE FOREIGN KEY FOR TABLE HOCVIEN
ALTER TABLE HOCVIEN
ADD CONSTRAINT FK_HOCVIEN_LOP FOREIGN KEY(MALOP) REFERENCES LOP(MALOP);

-- CREATE FOREIGN KEY FOR TABLE LOP
ALTER TABLE LOP
ADD CONSTRAINT FK_TRGLOP_HOCVIEN FOREIGN KEY(TRGLOP) REFERENCES HOCVIEN(MAHV);

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_GIAOVIEN FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV);

-- CREATE FOREIGN KEY FOR TABLE KHOA
ALTER TABLE KHOA
ADD CONSTRAINT FK_KHOA_GIAOVIEN FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV);

-- CREATE FOREIGN KEY FOR TABLE GIAOVIEN
ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GIAOVIEN_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);

-- CREATE FOREIGN KEY FOR TABLE MONHOC
ALTER TABLE MONHOC
ADD CONSTRAINT FK_MONHOC_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA);


-- CREATE FOREIGN KEY FOR TABLE GIANGDAY
ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GIANGDAY_LOP FOREIGN KEY (MALOP) REFERENCES LOP(MALOP);

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GIANGDAY_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GIANGDAY_GIAOVIEN FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV);

-- CREATE FOREIGN KEY FOR TABLE DIEUKIEN
ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DIEUKIEN_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DIEUKIEN_MONHOCTRUOC FOREIGN KEY (MAMH_TRUOC) REFERENCES MONHOC(MAMH);

-- CREATE FOREIGN KEY FOR TABLE KETQUATHI
ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KETQUATHI_HOCVIEN FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV);

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KETQUATHI_MONHOC FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH);

-- ALTER TABLE HOCVIEN
ALTER TABLE HOCVIEN
ADD GHICHU VARCHAR(100);

ALTER TABLE HOCVIEN
ADD DIEMTB NUMERIC(4,2);

ALTER TABLE HOCVIEN
ADD XEPLOAI VARCHAR(10);

-- INSERT DATA

INSERT INTO HOCVIEN (MAHV, HO, TEN, NGSINH, GIOITINH, NOISINH, MALOP) VALUES
('K1101', 'Nguyen Van', 'A', '1986-01-27', 'Nam', 'TpHCM', 'K11'),
('K1102', 'Tran Ngoc', 'Han', '1986-03-14', 'Nu', 'Kien Giang', 'K11'),
('K1103', 'Ha Duy', 'Lap', '1986-04-18', 'Nam', 'Nghe An', 'K11'),
('K1104', 'Tran Ngoc', 'Linh', '1986-03-30', 'Nu', 'Tay Ninh', 'K11'),
('K1105', 'Tran Minh', 'Long', '1986-02-27', 'Nam', 'TpHCM', 'K11'),
('K1106', 'Le Nhat', 'Minh', '1986-01-24', 'Nam', 'TpHCM', 'K11'),
('K1107', 'Nguyen Nhu', 'Nhut', '1986-01-27', 'Nam', 'Ha Noi', 'K11'),
('K1108', 'Nguyen Manh', 'Tam', '1986-02-27', 'Nam', 'Kien Giang', 'K11'),
('K1109', 'Phan Thi Thanh', 'Tam', '1986-01-27', 'Nu', 'Vinh Long', 'K11'),
('K1110', 'Le Hoai', 'Thuong', '1986-02-05', 'Nu', 'Can Tho', 'K11'),
('K1111', 'Le Ha', 'Vinh', '1986-12-25', 'Nam', 'Vinh Long', 'K11'),
('K1201', 'Nguyen Van', 'B', '1986-02-11', 'Nam', 'TpHCM', 'K12'),
('K1202', 'Nguyen Thi Kim', 'Duyen', '1986-01-18', 'Nu', 'TpHCM', 'K12'),
('K1203', 'Tran Thi Kim', 'Duyen', '1986-09-17', 'Nu', 'TpHCM', 'K12'),
('K1204', 'Truong My', 'Hanh', '1986-05-19', 'Nu', 'Dong Nai', 'K12'),
('K1205', 'Nguyen Thanh', 'Nam', '1986-04-17', 'Nam', 'TpHCM', 'K12'),
('K1206', 'Nguyen Thi Truc', 'Thanh', '1986-03-04', 'Nu', 'Kien Giang', 'K12'),
('K1207', 'Tran Thi Bich', 'Thuy', '1986-02-08', 'Nu', 'Nghe An', 'K12'),
('K1208', 'Huynh Thi Kim', 'Trieu', '1986-04-08', 'Nu', 'Tay Ninh', 'K12'),
('K1209', 'Pham Thanh', 'Trieu', '1986-02-23', 'Nam', 'TpHCM', 'K12'),
('K1210', 'Ngo Thanh', 'Tuan', '1986-02-14', 'Nam', 'TpHCM', 'K12'),
('K1211', 'Do Thi', 'Xuan', '1986-03-09', 'Nu', 'Ha Noi', 'K12'),
('K1212', 'Le Thi Phi', 'Yen', '1986-03-12', 'Nu', 'TpHCM', 'K12'),
('K1301', 'Nguyen Thi Kim', 'Cuc', '1986-06-09', 'Nu', 'Kien Giang', 'K13'),
('K1302', 'Truong Thi My', 'Hien', '1986-03-18', 'Nu', 'Nghe An', 'K13'),
('K1303', 'Le Duc', 'Hien', '1986-03-21', 'Nam', 'Tay Ninh', 'K13'),
('K1304', 'Le Quang', 'Hien', '1986-04-18', 'Nam', 'TpHCM', 'K13'),
('K1305', 'Le Thi', 'Huong', '1986-03-27', 'Nu', 'TpHCM', 'K13'),
('K1306', 'Nguyen Thai', 'Huu', '1986-03-30', 'Nam', 'Ha Noi', 'K13'),
('K1307', 'Tran Minh', 'Man', '1986-05-28', 'Nam', 'TpHCM', 'K13'),
('K1308', 'Nguyen Hieu', 'Nghia', '1986-04-08', 'Nam', 'Kien Giang', 'K13'),
('K1309', 'Nguyen Trung', 'Nghia', '1987-01-18', 'Nam', 'Nghe An', 'K13'),
('K1310', 'Tran Thi Hong', 'Tham', '1986-04-22', 'Nu', 'Tay Ninh', 'K13'),
('K1311', 'Tran Minh', 'Thuc', '1986-04-04', 'Nam', 'TpHCM', 'K13'),
('K1312', 'Nguyen Thi Kim', 'Yen', '1986-09-07', 'Nu', 'TpHCM', 'K13');

-- Bai 2
CREATE TRIGGER trg_validate_mhv ON HOCVIEN
FOR INSERT
AS
BEGIN
    DECLARE @mahv CHAR(5);
    DECLARE @malop CHAR(3);
    DECLARE @count INT;
    SELECT @mahv,@malop = MAHV,MALOP FROM INSERTED;
    SELECT @count = COUNT(*) FROM HOCVIEN WHERE MALOP = @malop;
    PRINT @count;
    IF @mahv != @malop + CAST(@count + 1 as varchar(2))
    BEGIN
        PRINT N'Không thể thêm học viên vào lớp này'
        ROLLBACK TRAN
    end
END;

--Bai 3
ALTER TABLE HOCVIEN
ADD CONSTRAINT CHK_GIOITINH CHECK (GIOITINH IN ('Nam', 'Nu'));

--Bai 4
ALter TABLE
    KETQUATHI
ADD CONSTRAINT
    CHK_DIEM
CHECK (
    DIEM BETWEEN 0 AND 10
    AND RIGHT(CAST(DIEM AS VARCHAR),3) LIKE '.__'
);

--Bai 5
ALTER TABLE
    KETQUATHI
ADD CONSTRAINT
    CHK_KQUA
CHECK (
    (KQUA ='Dat' AND DIEM between 5 and 10)
    or
    (KQUA ='Khong dat' AND DIEM between 0 and 4.99)
);

--Bai 6
ALTER TABLE
    KETQUATHI
ADD CONSTRAINT
    CHK_LANTHI
CHECK (LANTHI <= 3);

--Bai 7
ALTER TABLE
    GIANGDAY
ADD CONSTRAINT
    CHK_HOCKY
CHECK (HOCKY <= 3);

--Bai 8
ALTER TABLE
    GIAOVIEN
ADD CONSTRAINT
    CHK_HOCVI
CHECK (HOCVI IN ('CN','KS','TS','Ths','PTS'));

--Bai 9
CREATE TRIGGER trg_validate_classleader ON LOP
FOR INSERT, UPDATE
AS
BEGIN
    DECLARE @trglop CHAR(5)
    DECLARE @malop CHAR(3)
    DECLARE @mahv CHAR(5)
    SELECT @trglop,@malop = TRGLOP,MALOP FROM INSERTED
    SELECT @mahv = MAHV FROM HOCVIEN WHERE HOCVIEN.MALOP= @malop

    IF @trglop NOT IN @mahv
    BEGIN
        PRINT N'học sinh này không thuộc lớp'
        ROLLBACK TRAN
    END
END;

--Bai 10
CREATE TRIGGER trg_validate_trgkhoa ON KHOA
FOR INSERT, UPDATE
AS
BEGIN
    DECLARE @trgkhoa CHAR(5)
    DECLARE @makhoa CHAR(3)
    DECLARE @hocvi VARCHAR(10)
    SELECT @trgkhoa,@makhoa = TRGKHOA,MAKHOA FROM INSERTED
    SELECT @hocvi = HOCVI FROM GIAOVIEN WHERE @trgkhoa = MAGV

    IF @hocvi NOT IN ('TS','PTS')
    BEGIN
        PRINT N'Học vị của trường khoa không phù hợp'
        ROLLBACK TRAN
    END
END;

--Bai 11
ALTER TABLE
    HOCVIEN
ADD CONSTRAINT
    CHK_TUOI
CHECK
    (YEAR(GETDATE())-YEAR(NGSINH) >= 18);

--Bai 12
ALTER TABLE
    GIANGDAY
ADD CONSTRAINT
    CHK_NGAYBATDAU
CHECK
    (TUNGAY < DENNGAY);

--Bai 13
ALTER TABLE
    GIAOVIEN
ADD CONSTRAINT
    CHK_TUOI
CHECK
    (YEAR(GETDATE())-YEAR(NGSINH)>2);

--Bai 14
ALTER TABLE
    MONHOC
ADD CONSTRAINT
    CHK_CHENHLECHTC
CHECK
    (ABS(TCTH- TCLT) < 3);

--Bai 15
CREATE TRIGGER trg_kiem_tra_ngay_thi ON KETQUATHI
FOR UPDATE, INSERT
AS
BEGIN
    DECLARE @mahv CHAR(5)
    DECLARE @malop CHAR(3)
    DECLARE @mamh VARCHAR(10)
    DECLARE @ngaykt DATETIME
    DECLARE @ngaythi DATETIME

    SELECT @mahv,@mamh,@ngaythi = MAHV,MAMH,NGTHI FROM INSERTED
    SELECT @malop = MALOP FROM HOCVIEN WHERE @mahv = MAHV
    SELECT @ngaykt = DENNGAY FROM GIANGDAY WHERE @malop = MALOP AND @mamh = MAMH
    IF @ngaykt >= @ngaythi
    BEGIN
        ROLLBACK TRAN
    END
END
GO




