CREATE DATABASE DEONTAP2
USE DEONTAP2

CREATE TABLE NHANVIEN(
    MANV CHAR(5) PRIMARY KEY ,
    HOTEN VARCHAR(20),
    NGAYVL SMALLDATETIME,
    HSLUONG NUMERIC(4,2),
    MAPHONG CHAR(5)
)

CREATE TABLE PHONGBAN (
    MAPHONG CHAR(5) PRIMARY KEY ,
    TENPHONG VARCHAR(25),
    TRUONGPHONG CHAR(5)
)

CREATE TABLE XE(
    MAXE CHAR(5) PRIMARY KEY ,
    LOAIXE VARCHAR(20),
    SOCHONGOI INT,
    NAMSX INT,
)

CREATE TABLE PHANCONG(
    MAPC CHAR(5) PRIMARY KEY ,
    MANV CHAR(5),
    MAXE CHAR(5),
    NGAYDI SMALLDATETIME,
    NGAYVE SMALLDATETIME,
    NOIDEN VARCHAR(25)
)

ALTER TABLE PHONGBAN
ADD CONSTRAINT FK_TRG_PH FOREIGN KEY(TRUONGPHONG) REFERENCES NHANVIEN(MANV)

ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PC_NV FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)

ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PC_XE FOREIGN KEY(MAXE) REFERENCES XE(MAXE)
--CAU 2
ALTER TABLE XE
ADD CONSTRAINT CHK_LOAIXE_NSX
CHECK (
    LOAIXE = 'TOYOTA' AND NAMSX <= 2006
    OR LOAIXE != 'TOYOTA'
    )

CREATE OR ALTER TRIGGER TRG_PC_PHGNGTH ON PHANCONG
    FOR INSERT , UPDATE
    AS
    BEGIN
        DECLARE @MANV CHAR(5),@TENPHONG VARCHAR(25), @MAPHONG CHAR(5), @LOAIXE VARCHAR(20), @MAXE CHAR(5)
        SELECT @MANV = MANV,@MAXE = MAXE FROM inserted
        SELECT @LOAIXE = LOAIXE FROM XE WHERE MAXE = @MAXE
        SELECT @MAPHONG = MAPHONG FROM NHANVIEN WHERE @MANV = MANV
        SELECT @TENPHONG = TENPHONG FROM PHONGBAN WHERE @MAPHONG = MAPHONG
        IF (@TENPHONG = 'NGOAI THANH' AND @LOAIXE != 'TOYOTA')
        BEGIN
            PRINT 'NHAN VIEN PHONG NGOAI THANH CHI DUOC PHAN XE TOYOTA'
            ROLLBACK TRANSACTION
        END
    END
GO
--CAU 3

SELECT NV.MANV, HOTEN
FROM
    NHANVIEN NV INNER JOIN PHONGBAN PB ON NV.MAPHONG = PB.MAPHONG
                INNER JOIN PHANCONG P on NV.MANV = P.MANV
                INNER JOIN XE X on P.MAXE = X.MAXE
WHERE TENPHONG='NOI THANH' AND LOAIXE ='TOYOTA' AND SOCHONGOI = 4

SELECT MANV, HOTEN
FROM NHANVIEN INNER JOIN
    (SELECT P.TRUONGPHONG
    FROM NHANVIEN NV INNER JOIN PHONGBAN P on NV.MAPHONG = P.MAPHONG
    WHERE NOT EXISTS(
        SELECT *
        FROM PHANCONG
        WHERE NV.MANV = MANV AND NOT EXISTS(
            SELECT *
            FROM XE
            WHERE PHANCONG.MAXE = MAXE
        )
    )) AS KQ1 ON NHANVIEN.MANV = KQ1.TRUONGPHONG

SELECT COUNT(*) SL
FROM NHANVIEN NV INNER JOIN PHANCONG P on NV.MANV = P.MANV
                 INNER JOIN XE X on P.MAXE = X.MAXE
WHERE LOAIXE = 'TOYOTA'
GROUP BY NV.MAPHONG, NV.MANV


SELECT NV.MANV, HOTEN
    FROM NHANVIEN NV INNER JOIN PHANCONG P on NV.MANV = P.MANV
                     INNER JOIN XE X on P.MAXE = X.MAXE
    WHERE LOAIXE = 'TOYOTA'
    GROUP BY NV.MAPHONG, NV.MANV, HOTEN
    HAVING COUNT(*) <= ALL (
            SELECT SL
            FROM
            (SELECT MAPHONG,COUNT(*) SL
            FROM NHANVIEN NV INNER JOIN PHANCONG P on NV.MANV = P.MANV
                             INNER JOIN XE X on P.MAXE = X.MAXE
            WHERE LOAIXE = 'TOYOTA'
            GROUP BY NV.MAPHONG, NV.MANV) AS KQ
            WHERE KQ.MAPHONG = NV.MAPHONG
    )

