CREATE DATABASE DEONTAP4

USE DEONTAP4

CREATE TABLE KHACHHANG
(
	MAKH CHAR(5) PRIMARY KEY,
	HOTEN VARCHAR(30),
	DIACHI VARCHAR(30),
	SODT VARCHAR(15),
	LOAIKH VARCHAR(10),
)


CREATE TABLE BANG_DIA
(
	MABD CHAR(5) PRIMARY KEY,
	TENBD VARCHAR(25),
	THELOAI VARCHAR(25),
)


CREATE TABLE PHIEUTHUE
(
	MAPT CHAR(5) PRIMARY KEY,
	MAKH CHAR(5),
	NGAYTHUE SMALLDATETIME,
	NGAYTRA SMALLDATETIME,
	SOLUONGTHUE INT,
	CONSTRAINT FK_PT_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
)
GO

--CAU 2
CREATE TABLE CHITIET_PM
(
	MAPT CHAR(5),
	MABD CHAR(5),
	CONSTRAINT PK_CT PRIMARY KEY (MAPT, MABD),
	CONSTRAINT FK_CT_PT FOREIGN KEY (MAPT) REFERENCES PHIEUTHUE(MAPT),
	CONSTRAINT FK_CT_BD FOREIGN KEY (MABD) REFERENCES BANG_DIA(MABD),
)


ALTER TABLE BANG_DIA
ADD CONSTRAINT CHK_THELOAI_BANG_DIA CHECK (THELOAI IN ('CA NHAC', 'PHIM HANH DONG', 'PHIM TINH CAM', 'PHIM HOAT HINH'))


CREATE OR ALTER TRIGGER TRG_UPDATE_KHACHHANG ON KHACHHANG
    FOR UPDATE
    AS
    BEGIN
        DECLARE @MAKH CHAR(5), @LOAIKH VARCHAR(10)
        SELECT @MAKH = MAKH, @LOAIKH = LOAIKH FROM inserted

        IF (@LOAIKH != 'VIP'
                AND EXISTS (SELECT *
                            FROM PHIEUTHUE
                            WHERE MAKH = @MAKH AND SOLUONGTHUE > 5))
        BEGIN
            PRINT 'CHI CO KHACH HANG VIP MOI DUOC THUE TREN 5 DIA'
            ROLLBACK TRAN
        END
    END

CREATE OR ALTER TRIGGER TRG_UPDATE_PHIEUTHUE ON PHIEUTHUE
    FOR INSERT, UPDATE
    AS
    BEGIN
        DECLARE @MAKH CHAR(5), @SOLUONGTHUE INT, @LOAIKH VARCHAR(10)
        SELECT @MAKH = MAKH, @SOLUONGTHUE = SOLUONGTHUE
        FROM inserted

        SELECT @LOAIKH = LOAIKH
        FROM KHACHHANG
        WHERE MAKH = @MAKH

        IF (@LOAIKH != 'VIP' AND @SOLUONGTHUE > 5)
        BEGIN
            PRINT 'CHI CO KHACH HANG VIP MOI DUOC THUE TREN 5 DIA'
            ROLLBACK TRAN
        END

    END


SELECT KH.MAKH, KH.HOTEN
FROM KHACHHANG KH INNER JOIN PHIEUTHUE PT ON KH.MAKH = PT.MAKH
                  INNER JOIN CHITIET_PM CT ON PT.MAPT = CT.MAPT
                  INNER JOIN BANG_DIA BD ON CT.MABD = BD.MABD
WHERE BD.THELOAI = 'TINH CAM' AND PT.SOLUONGTHUE > 3


SELECT KH.MAKH, KH.HOTEN
FROM KHACHHANG KH
INNER JOIN PHIEUTHUE PT ON KH.MAKH = PT.MAKH
WHERE KH.LOAIKH = 'VIP'
GROUP BY KH.MAKH, KH.HOTEN
HAVING SUM(PT.SOLUONGTHUE) >= ALL
       (
            SELECT SUM(PT.SOLUONGTHUE)
            FROM KHACHHANG KH1
            INNER JOIN PHIEUTHUE PT1 ON KH1.MAKH = PT1.MAKH
            WHERE KH1.LOAIKH = 'VIP'
            GROUP BY KH1.MAKH
        )


SELECT BD.THELOAI, KH.HOTEN
FROM KHACHHANG KH
INNER JOIN PHIEUTHUE PT ON KH.MAKH = PT.MAKH
INNER JOIN CHITIET_PM CT ON PT.MAPT = CT.MAPT
INNER JOIN BANG_DIA BD ON CT.MABD = BD.MABD
GROUP BY BD.THELOAI, KH.HOTEN
HAVING COUNT(*) >= ALL
            (
                SELECT COUNT(*)
                FROM KHACHHANG KH1
                INNER JOIN PHIEUTHUE PT1 ON KH1.MAKH = PT1.MAKH
                INNER JOIN CHITIET_PM CT1 ON PT1.MAPT = CT1.MAPT
                INNER JOIN BANG_DIA BD1 ON CT1.MABD = BD1.MABD
                WHERE BD.THELOAI = BD1.THELOAI
                GROUP BY BD1.THELOAI, KH1.HOTEN
            )