CREATE DATABASE DEONTAP3

USE DEONTAP3

CREATE TABLE DOCGIA
(
	MADG CHAR(5) PRIMARY KEY,
	HOTEN VARCHAR(30),
	NGAYSINH SMALLDATETIME,
	DIACHI VARCHAR(30),
	SODT VARCHAR(15)
)

CREATE TABLE SACH
(
	MASACH CHAR(5) PRIMARY KEY,
	TENSACH VARCHAR(25),
	THELOAI VARCHAR(25),
	NHAXUATBAN VARCHAR(30)
)

CREATE TABLE PHIEUTHUE
(
	MAPT CHAR(5) PRIMARY KEY,
	MADG CHAR(5),
	NGAYTHUE SMALLDATETIME,
	NGAYTRA SMALLDATETIME,
	SOSACHTHUE INT
)
CREATE TABLE CHITIET_PT
(
	MAPT CHAR(5),
	MASACH CHAR(5),
	CONSTRAINT PK_CHITIET_PT PRIMARY KEY (MAPT, MASACH)
)

ALTER TABLE PHIEUTHUE
ADD CONSTRAINT FK_MADG_PHIEUTHUE FOREIGN KEY (MADG) REFERENCES DOCGIA(MADG)

ALTER TABLE CHITIET_PT
ADD CONSTRAINT FK_MAPT_CHITIET_PT FOREIGN KEY (MAPT) REFERENCES PHIEUTHUE(MAPT)

ALTER TABLE CHITIET_PT
ADD CONSTRAINT FK_MASACH_CHITIET_PT FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)


--CAU2
CREATE OR ALTER TRIGGER TRG_UPDATE_PHIEUTHUE ON PHIEUTHUE
    FOR UPDATE
    AS
    BEGIN
        DECLARE @NGAYTHUE DATETIME, @NGAYTRA DATETIME

        SELECT @NGAYTHUE = NGAYTHUE, @NGAYTRA = NGAYTRA FROM INSERTED

        IF(@NGAYTHUE IS NOT NULL)
        BEGIN
            IF(DATEDIFF(DAY, @NGAYTRA, @NGAYTHUE) > 10 )
            BEGIN
                PRINT 'KHONG DUOC THUE QUA 10 NGAY'
                ROLLBACK TRANSACTION
            END
        END


    END



CREATE OR ALTER TRIGGER TRG_INSERT_PHIEUTHUE ON PHIEUTHUE
    FOR INSERT
    AS
    BEGIN
        DECLARE @MAPT CHAR(5)

        SELECT @MAPT = MAPT
        FROM inserted

        UPDATE PHIEUTHUE
        SET SOSACHTHUE = 0
        WHERE MAPT = @MAPT

    END

GO
CREATE OR ALTER TRIGGER TRG_INSERT_CHITIET_PT ON CHITIET_PT
    FOR INSERT
    AS
    BEGIN
        DECLARE @MAPT CHAR(5)

        SELECT @MAPT = MAPT FROM inserted

        UPDATE PHIEUTHUE
        SET SOSACHTHUE = SOSACHTHUE + 1
        WHERE MAPT = @MAPT
    END

GO
CREATE OR ALTER TRIGGER TRG_DELETE_CHITIET_PT ON CHITIET_PT
    FOR DELETE
    AS
    BEGIN
        DECLARE @MAPT CHAR(5)
        SELECT @MAPT = MAPT FROM deleted
        UPDATE PHIEUTHUE
        SET SOSACHTHUE = SOSACHTHUE - 1
        WHERE MAPT = @MAPT
    END

GO
CREATE OR ALTER TRIGGER TRG_UPDATE_CHITIET_PT ON CHITIET_PT
    FOR UPDATE
    AS
    BEGIN
        DECLARE @MAPTMOI CHAR(5),@MAPTCU CHAR(5)

        SELECT @MAPTMOI = MAPT FROM inserted

        SELECT @MAPTCU = MAPT FROM deleted

        UPDATE PHIEUTHUE
        SET SOSACHTHUE = SOSACHTHUE + 1
        WHERE MAPT = @MAPTMOI

        UPDATE PHIEUTHUE
        SET SOSACHTHUE = SOSACHTHUE - 1
        WHERE MAPT = @MAPTCU
    END

--CAU 3
SELECT DG.MADG, DG.HOTEN
FROM DOCGIA DG  INNER JOIN PHIEUTHUE PT ON PT.MADG = DG.MADG
                INNER JOIN CHITIET_PT CT ON CT.MAPT = PT.MAPT
                INNER JOIN SACH S ON S.MASACH = CT.MASACH
WHERE THELOAI  ='TIN HOC' AND YEAR(NGAYTHUE) = 2007

SELECT DG.MADG, DG.HOTEN
FROM DOCGIA DG INNER JOIN PHIEUTHUE PT ON PT.MADG = DG.MADG
               INNER JOIN CHITIET_PT CT ON CT.MAPT = PT.MAPT
               INNER JOIN SACH S ON S.MASACH = CT.MASACH
GROUP BY DG.MADG, DG.HOTEN
HAVING COUNT(DISTINCT THELOAI) >= ALL
       (
            SELECT COUNT(DISTINCT THELOAI)
           FROM DOCGIA DG1
           INNER JOIN PHIEUTHUE PT1 ON PT1.MADG = DG1.MADG
           INNER JOIN CHITIET_PT CT1 ON CT1.MAPT = PT1.MAPT
           INNER JOIN SACH S1 ON S1.MASACH = CT1.MASACH
           GROUP BY DG1.MADG, DG1.HOTEN
        )


SELECT S.THELOAI, S.TENSACH
FROM SACH S
INNER JOIN CHITIET_PT CT ON CT.MASACH = S.MASACH
GROUP BY S.THELOAI, S.TENSACH
HAVING COUNT(MAPT) >=  ALL
        (
           SELECT COUNT(MAPT)
            FROM SACH S1
            INNER JOIN CHITIET_PT CT1 ON CT1.MASACH = S1.MASACH
            WHERE S1.THELOAI = S.THELOAI
            GROUP BY S1.THELOAI, S1.TENSACH
        )