CREATE DATABASE ONTAP1
DROP  DATABASE ONTAP1
USE ONTAP1

CREATE TABLE TACGIA (
    MATG CHAR(5) PRIMARY KEY,
    HOTEN VARCHAR(20),
    DIACHI VARCHAR(50),
    NGSINH SMALLDATETIME,
    SODT VARCHAR(15),
)

CREATE TABLE SACH(
    MASACH CHAR(5) PRIMARY KEY,
    TENSACH VARCHAR(25),
    THELOAI VARCHAR(25),
)

CREATE TABLE TACGIA_SACH(
    MATG CHAR(5),
    MASACH CHAR(5),
    CONSTRAINT PK_TACGIA_SACH PRIMARY KEY (MATG,MASACH)
)

CREATE TABLE PHATHANH(
    MAPH CHAR(5) ,
    MASACH CHAR(5),
    NGAYPH SMALLDATETIME,
    SOLUONG INT,
    NHAXUATBAN VARCHAR(20),
)

ALTER TABLE TACGIA_SACH
ADD CONSTRAINT FK_TGS_MASACH FOREIGN KEY(MASACH) REFERENCES SACH(MASACH)

ALTER TABLE TACGIA_SACH
ADD CONSTRAINT FK_TGS_TACGIA FOREIGN KEY(MATG) REFERENCES TACGIA(MATG)

ALTER TABLE PHATHANH
ADD CONSTRAINT FK_PHATHANH_SACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)

-- CAU 2
CREATE OR ALTER TRIGGER TRG_NGSINH_TG_NGPHATHANH ON PHATHANH
    FOR INSERT , UPDATE
    AS
    BEGIN
        DECLARE @MASACH CHAR(5), @NGAYPH SMALLDATETIME, @MATG CHAR(5), @NGSINH SMALLDATETIME
        SELECT @MASACH = MASACH, @NGAYPH = NGAYPH FROM inserted
        SELECT @MATG = MATG FROM TACGIA_SACH WHERE @MASACH = MASACH
        SELECT @NGSINH = NGSINH FROM TACGIA WHERE @MATG = MATG
        IF (@NGAYPH >= @NGSINH)
        BEGIN
            PRINT 'NGAY PHAT HANH PHAI NHO HON NGAY SINH CUA TAC GIA'
            ROLLBACK TRAN
        END
    END

CREATE OR ALTER TRIGGER TRG_SACH_NHAPHATHANH ON PHATHANH
    FOR INSERT , UPDATE
    AS
    BEGIN
        DECLARE @MASACH CHAR(5), @NXB VARCHAR(20), @THELOAI VARCHAR(25)
        SELECT @MASACH = MASACH, @NXB = NHAXUATBAN FROM INSERTED
        SELECT @THELOAI FROM SACH WHERE @MASACH = MASACH
        IF (@THELOAI = 'GIAO KHOA' AND @NXB != 'GIAODUC')
        BEGIN
            PRINT 'SACH GIAO KHOA CHI DUOC NHA XUAT BAN GIAO DUC PHAT HANH'
            ROLLBACK TRAN
        END
    END

--CAU 3
SELECT TG.MATG, HOTEN, SODT
FROM TACGIA TG INNER JOIN  TACGIA_SACH TS on TG.MATG = TS.MATG
               INNER JOIN  SACH S ON S.MASACH = TS.MASACH
               INNER JOIN PHATHANH PH ON PH.MASACH = TS.MASACH
WHERE S.THELOAI = 'VAN HOC' AND PH.NHAXUATBAN = 'TRE'

SELECT TOP 1 WITH TIES NHAXUATBAN
FROM PHATHANH PH INNER JOIN SACH S ON PH.MASACH = S.MASACH
GROUP BY NHAXUATBAN
ORDER BY COUNT(S.THELOAI) DESC


SELECT NHAXUATBAN, MATG
FROM
    (SELECT NHAXUATBAN, TS.MATG, COUNT (*) AS SLPH
    FROM TACGIA_SACH TS INNER JOIN PHATHANH P on TS.MASACH = P.MASACH
    GROUP BY NHAXUATBAN, TS.MATG) AS KQ1
WHERE SLPH >= ALL (
        SELECT KQ2.SLPH
        FROM
            (SELECT NHAXUATBAN, TS.MATG, COUNT (*) AS SLPH
            FROM TACGIA_SACH TS INNER JOIN PHATHANH P on TS.MASACH = P.MASACH
            GROUP BY NHAXUATBAN, TS.MATG) AS KQ2
        WHERE KQ1.NHAXUATBAN = KQ2.NHAXUATBAN
    )







